# Generated by Django 4.1.3 on 2023-05-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_location_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='testdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hum', models.DecimalField(decimal_places=6, max_digits=9)),
                ('temp', models.DecimalField(decimal_places=6, max_digits=9)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
