# Generated by Django 4.1.3 on 2023-05-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_testdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testdb',
        ),
    ]
