# Generated by Django 4.1.3 on 2023-05-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_delete_testdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSGetPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.RenameModel(
            old_name='Location',
            new_name='locationASV',
        ),
    ]
