# Generated by Django 4.1.3 on 2023-05-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_gpsgetpoint_rename_location_locationasv'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humdinity', models.DecimalField(decimal_places=6, max_digits=9)),
                ('temperature', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dissolvedOxygen', models.DecimalField(decimal_places=6, max_digits=9)),
                ('airPressure', models.DecimalField(decimal_places=6, max_digits=9)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
