# Generated by Django 4.1.3 on 2023-05-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_locationasv_data_from_gps_to_web_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Push_Data_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humdinity', models.DecimalField(decimal_places=6, max_digits=9)),
                ('temperature', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
