# Generated by Django 4.1.3 on 2023-05-17 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_sensordata_delete_push_data_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
