# Generated by Django 4.1.3 on 2023-05-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_sensordata_temperature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_From_Sensor',
        ),
    ]
