# Generated by Django 4.1.3 on 2023-05-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_delete_data_from_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_From_Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humdinity', models.DecimalField(decimal_places=6, max_digits=9)),
                ('temperature', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dissolvedOxygen', models.DecimalField(decimal_places=6, max_digits=9)),
                ('airPressure', models.DecimalField(decimal_places=6, max_digits=9)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
