# Generated by Django 4.1.3 on 2023-06-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_data_from_asv_delete_data_from_gps_to_web_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_from_asv',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='data_from_asv',
            name='airPressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_from_asv',
            name='dissolvedOxygen',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_from_asv',
            name='humdinity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_from_asv',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_from_asv',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_from_asv',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
