# Generated by Django 4.1.3 on 2023-06-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_rename_humdinity_data_from_asv_humidity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
